plugins:
  - skipBotEvents: true
    uses:
      # conversation-plugin
      plugin: codebestiatestorg/conversation-rewards
      with:
        logLevel: "info"
        evmNetworkId: 100
        evmPrivateEncrypted: "encrypted-key"
        erc20RewardToken: "0xe91D153E0b41518A2Ce8Dd3D7944Fa863463a97d"
        dataCollection:
          maxAttempts: 10
          delayMs: 10000
        incentives:
          requirePriceLabel: true
          contentEvaluator:
            openAi:
              model: "gpt-4o"
              endpoint: "https://api.openai.com/v1"
            multipliers:
              - role: [ISSUE_SPECIFICATION]
                relevance: 1
              - role: [PULL_AUTHOR]
                relevance: 1
              - role: [PULL_ASSIGNEE]
                relevance: 1
              - role: [PULL_COLLABORATOR]
                relevance: 1
              - role: [PULL_CONTRIBUTOR]
                relevance: 1
          userExtractor:
            redeemTask: true
          dataPurge: {}
          formattingEvaluator:
            wordCountExponent: 0.85
            multipliers:
              - role: ["ISSUE_SPECIFICATION"]
                multiplier: 1
                rewards:
                  html:
                    br: { score: 0, countWords: true }
                    code: { score: 5, countWords: false }
                    p: { score: 0, countWords: true }
                    em: { score: 0, countWords: true }
                    img: { score: 5, countWords: true }
                    strong: { score: 0, countWords: false }
                    blockquote: { score: 0, countWords: false }
                    h1: { score: 1, countWords: true }
                    h2: { score: 1, countWords: true }
                    h3: { score: 1, countWords: true }
                    h4: { score: 1, countWords: true }
                    h5: { score: 1, countWords: true }
                    h6: { score: 1, countWords: true }
                    a: { score: 5, countWords: true }
                    li: { score: 0.5, countWords: true }
                    ul: { score: 1, countWords: true }
                    td: { score: 0, countWords: true }
                    hr: { score: 0, countWords: true }
                    pre: { score: 0, countWords: false }
                    ol: { score: 1, countWords: true }
                  wordValue: 0.1
              - role: ["ISSUE_AUTHOR"]
                multiplier: 1
                rewards:
                  html:
                    br: { score: 0, countWords: true }
                    code: { score: 5, countWords: false }
                    p: { score: 0, countWords: true }
                    em: { score: 0, countWords: true }
                    img: { score: 5, countWords: true }
                    strong: { score: 0, countWords: false }
                    blockquote: { score: 0, countWords: false }
                    h1: { score: 1, countWords: true }
                    h2: { score: 1, countWords: true }
                    h3: { score: 1, countWords: true }
                    h4: { score: 1, countWords: true }
                    h5: { score: 1, countWords: true }
                    h6: { score: 1, countWords: true }
                    a: { score: 5, countWords: true }
                    li: { score: 0.5, countWords: true }
                    ul: { score: 1, countWords: true }
                    td: { score: 0, countWords: true }
                    hr: { score: 0, countWords: true }
                    pre: { score: 0, countWords: false }
                    ol: { score: 1, countWords: true }
                  wordValue: 0.2
              - role: ["ISSUE_ASSIGNEE"]
                multiplier: 0
                rewards:
                  html:
                    br: { score: 0, countWords: true }
                    code: { score: 5, countWords: false }
                    p: { score: 0, countWords: true }
                    em: { score: 0, countWords: true }
                    img: { score: 5, countWords: true }
                    strong: { score: 0, countWords: false }
                    blockquote: { score: 0, countWords: false }
                    h1: { score: 1, countWords: true }
                    h2: { score: 1, countWords: true }
                    h3: { score: 1, countWords: true }
                    h4: { score: 1, countWords: true }
                    h5: { score: 1, countWords: true }
                    h6: { score: 1, countWords: true }
                    a: { score: 5, countWords: true }
                    li: { score: 0.5, countWords: true }
                    ul: { score: 1, countWords: true }
                    td: { score: 0, countWords: true }
                    hr: { score: 0, countWords: true }
                    pre: { score: 0, countWords: false }
                    ol: { score: 1, countWords: true }
                  wordValue: 0
              - role: ["ISSUE_COLLABORATOR"]
                multiplier: 1
                rewards:
                  html:
                    br: { score: 0, countWords: true }
                    code: { score: 5, countWords: false }
                    p: { score: 0, countWords: true }
                    em: { score: 0, countWords: true }
                    img: { score: 5, countWords: true }
                    strong: { score: 0, countWords: false }
                    blockquote: { score: 0, countWords: false }
                    h1: { score: 1, countWords: true }
                    h2: { score: 1, countWords: true }
                    h3: { score: 1, countWords: true }
                    h4: { score: 1, countWords: true }
                    h5: { score: 1, countWords: true }
                    h6: { score: 1, countWords: true }
                    a: { score: 5, countWords: true }
                    li: { score: 0.5, countWords: true }
                    ul: { score: 1, countWords: true }
                    td: { score: 0, countWords: true }
                    hr: { score: 0, countWords: true }
                    pre: { score: 0, countWords: false }
                    ol: { score: 1, countWords: true }
                  wordValue: 0.1
              - role: ["ISSUE_CONTRIBUTOR"]
                multiplier: 0.25
                rewards:
                  html:
                    br: { score: 0, countWords: true }
                    code: { score: 5, countWords: false }
                    p: { score: 0, countWords: true }
                    em: { score: 0, countWords: true }
                    img: { score: 5, countWords: true }
                    strong: { score: 0, countWords: false }
                    blockquote: { score: 0, countWords: false }
                    h1: { score: 1, countWords: true }
                    h2: { score: 1, countWords: true }
                    h3: { score: 1, countWords: true }
                    h4: { score: 1, countWords: true }
                    h5: { score: 1, countWords: true }
                    h6: { score: 1, countWords: true }
                    a: { score: 5, countWords: true }
                    li: { score: 0.5, countWords: true }
                    ul: { score: 1, countWords: true }
                    td: { score: 0, countWords: true }
                    hr: { score: 0, countWords: true }
                    pre: { score: 0, countWords: false }
                    ol: { score: 1, countWords: true }
                  wordValue: 0.1
              - role: ["PULL_SPECIFICATION"]
                multiplier: 0
                rewards:
                  html:
                    br: { score: 0, countWords: true }
                    code: { score: 5, countWords: false }
                    p: { score: 0, countWords: true }
                    em: { score: 0, countWords: true }
                    img: { score: 5, countWords: true }
                    strong: { score: 0, countWords: false }
                    blockquote: { score: 0, countWords: false }
                    h1: { score: 1, countWords: true }
                    h2: { score: 1, countWords: true }
                    h3: { score: 1, countWords: true }
                    h4: { score: 1, countWords: true }
                    h5: { score: 1, countWords: true }
                    h6: { score: 1, countWords: true }
                    a: { score: 5, countWords: true }
                    li: { score: 0.5, countWords: true }
                    ul: { score: 1, countWords: true }
                    td: { score: 0, countWords: true }
                    hr: { score: 0, countWords: true }
                    pre: { score: 0, countWords: false }
                    ol: { score: 1, countWords: true }
                  wordValue: 0
              - role: ["PULL_AUTHOR"]
                multiplier: 2
                rewards:
                  html:
                    br: { score: 0, countWords: true }
                    code: { score: 5, countWords: false }
                    p: { score: 0, countWords: true }
                    em: { score: 0, countWords: true }
                    img: { score: 5, countWords: true }
                    strong: { score: 0, countWords: false }
                    blockquote: { score: 0, countWords: false }
                    h1: { score: 1, countWords: true }
                    h2: { score: 1, countWords: true }
                    h3: { score: 1, countWords: true }
                    h4: { score: 1, countWords: true }
                    h5: { score: 1, countWords: true }
                    h6: { score: 1, countWords: true }
                    a: { score: 5, countWords: true }
                    li: { score: 0.5, countWords: true }
                    ul: { score: 1, countWords: true }
                    td: { score: 0, countWords: true }
                    hr: { score: 0, countWords: true }
                    pre: { score: 0, countWords: false }
                    ol: { score: 1, countWords: true }
                  wordValue: 0.2
              - role: ["PULL_ASSIGNEE"]
                multiplier: 1
                rewards:
                  html:
                    br: { score: 0, countWords: true }
                    code: { score: 5, countWords: false }
                    p: { score: 0, countWords: true }
                    em: { score: 0, countWords: true }
                    img: { score: 5, countWords: true }
                    strong: { score: 0, countWords: false }
                    blockquote: { score: 0, countWords: false }
                    h1: { score: 1, countWords: true }
                    h2: { score: 1, countWords: true }
                    h3: { score: 1, countWords: true }
                    h4: { score: 1, countWords: true }
                    h5: { score: 1, countWords: true }
                    h6: { score: 1, countWords: true }
                    a: { score: 5, countWords: true }
                    li: { score: 0.5, countWords: true }
                    ul: { score: 1, countWords: true }
                    td: { score: 0, countWords: true }
                    hr: { score: 0, countWords: true }
                    pre: { score: 0, countWords: false }
                    ol: { score: 1, countWords: true }
                  wordValue: 0.1
              - role: ["PULL_COLLABORATOR"]
                multiplier: 1
                rewards:
                  html:
                    br: { score: 0, countWords: true }
                    code: { score: 5, countWords: false }
                    p: { score: 0, countWords: true }
                    em: { score: 0, countWords: true }
                    img: { score: 5, countWords: true }
                    strong: { score: 0, countWords: false }
                    blockquote: { score: 0, countWords: false }
                    h1: { score: 1, countWords: true }
                    h2: { score: 1, countWords: true }
                    h3: { score: 1, countWords: true }
                    h4: { score: 1, countWords: true }
                    h5: { score: 1, countWords: true }
                    h6: { score: 1, countWords: true }
                    a: { score: 5, countWords: true }
                    li: { score: 0.5, countWords: true }
                    ul: { score: 1, countWords: true }
                    td: { score: 0, countWords: true }
                    hr: { score: 0, countWords: true }
                    pre: { score: 0, countWords: false }
                    ol: { score: 1, countWords: true }
                  wordValue: 0.1
              - role: ["PULL_CONTRIBUTOR"]
                multiplier: 0.25
                rewards:
                  html:
                    br: { score: 0, countWords: true }
                    code: { score: 5, countWords: false }
                    p: { score: 0, countWords: true }
                    em: { score: 0, countWords: true }
                    img: { score: 5, countWords: true }
                    strong: { score: 0, countWords: false }
                    blockquote: { score: 0, countWords: false }
                    h1: { score: 1, countWords: true }
                    h2: { score: 1, countWords: true }
                    h3: { score: 1, countWords: true }
                    h4: { score: 1, countWords: true }
                    h5: { score: 1, countWords: true }
                    h6: { score: 1, countWords: true }
                    a: { score: 5, countWords: true }
                    li: { score: 0.5, countWords: true }
                    ul: { score: 1, countWords: true }
                    td: { score: 0, countWords: true }
                    hr: { score: 0, countWords: true }
                    pre: { score: 0, countWords: false }
                    ol: { score: 1, countWords: true }
                  wordValue: 0.1
            permitGeneration: {}
            githubComment:
              post: true
              debug: false
